# Generated by Django 2.2 on 2020-01-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
